Check if webpack-dev-server is in path

diff --git a/bin/wpc b/bin/wpc
--- a/bin/wpc
+++ b/bin/wpc
@@ -8,6 +8,12 @@ then
   exit 1
 fi
 
+if [ ! -x "$(command -v webpack-dev-server)" ]
+then
+  echo "Missing webpack-dev-server in path. Install it with yarn or npm"
+  exit 1
+fi
+
 if [ ! -z "NODE_PATH" ]
 then
   local_node_modules="$PWD/node_modules"
